rootProject.name = "IridiumSkyblock"
include("plugin")
include("multiversion")
include("multiversion:common")
include("multiversion:v1_16_R3")
include("multiversion:v1_16_R2")
include("multiversion:v1_16_R1")
include("multiversion:v1_15_R1")
include("multiversion:v1_14_R1")
include("multiversion:v1_13_R2")
include("multiversion:v1_13_R1")
include("multiversion:v1_12_R1")
include("multiversion:v1_11_R1")
include("multiversion:v1_10_R1")
include("multiversion:v1_9_R2")
include("multiversion:v1_9_R1")
include("multiversion:v1_8_R3")
include("multiversion:v1_8_R2")