name: IridiumSkyblock
version: 3.0.0
description: Skyblock Redifined
main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13'
author: Peaches_MLG
commands:
  iridiumskyblock:
    aliases: [ "island", is ]
    description: Main plugin command