name: IridiumSkyblock
version: ${version}
description: Skyblock Redifined
main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13'
author: Peaches_MLG
depend: [ Vault ]
softdepend: [ "MVdWPlaceholderAPI","PlaceholderAPI" ]
commands:
  iridiumskyblock:
    aliases: [ "island", is ]
    description: Main plugin command
